// Generated by CoffeeScript 2.5.1
(function() {
  var React, hl;

  React = require('react');

  hl = require('prism-react-renderer');

  module.exports = function(props) {
    return React.createElement(hl.default, {
      ...hl.defaultProps,
      code: props.children,
      language: props.lang
    }, function({className, style, tokens, getLineProps, getTokenProps}) {
      return React.createElement('pre', {
        className,
        style: {
          ...style,
          margin: 0,
          padding: '5px'
        }
      }, [
        tokens.map(function(line,
        i) {
          return React.createElement('div',
        {...getLineProps({
              line,
              key: i
            })},
        [
            line.map(function(token,
            key) {
              return React.createElement('span',
            {...getTokenProps({token,
            key})});
            })
          ]);
        })
      ]);
    });
  };

}).call(this);
