name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install nix
      uses: cachix/install-nix-action@v22

    - name: setup cachix
      uses: cachix/cachix-action@v12
      with:
        name: anillc
        authToken: ${{ secrets.CACHIX_TOKEN }}

    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: nix build .