name: docker push

on: [push, workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          username: anillc
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        run: |
          echo id: $(git rev-parse --short HEAD)
          docker buildx build \
            --tag anillc/cllina:latest \
            --tag anillc/cllina:$(git rev-parse --short HEAD) \
            --output "type=image,push=true" \
            .